//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities.Relacional
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserModule
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdModule { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
    }
}
